github action: add test reporter

diff --git a/.github/workflows/unitt-test.yml b/.github/workflows/unitt-test.yml
--- a/.github/workflows/unitt-test.yml
+++ b/.github/workflows/unitt-test.yml
@@ -45,6 +45,11 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Make repo safe
+        run: |
+            git config --global --add safe.directory /__w/TOMs/TOMs
+
+
       - name: Install system packages
         run: |
             apt-get update && apt-get install -y libpq-dev gcc postgresql-client-${POSTGRES_VERSION} unixodbc-dev g++
@@ -90,3 +95,11 @@ jobs:
         with:
           name: python-coverage-results
           path: coverage-reports/coverage-unit.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Python Tests            # Name of the check run which will be created
+          path: junit/test-results-unit.xml
+          reporter: java-junit
